<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!--

Document History:

======== Version 0.1 ====================================
	i. Document Created 01/04/2009

======== Version 0.2 ====================================
	ii. Document updated 06/01/2020
		Updated wsdl for SOAP version 1.2
		
-->

<wsdl:definitions 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
	xmlns:ackreq="http://www.ros.ie/schemas/customs/acknowledgerequest/v1" 
	xmlns:ackres="http://www.ros.ie/schemas/customs/acknowledgeresponse/v1" 
	xmlns="http://www.ros.ie/schemas/customs/service/mailboxAcknowledge" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.ros.ie/schemas/customs/service/mailboxAcknowledge" 
	name="mailboxAcknowledgeService">


	<wsdl:types>
		<xs:schema><xs:import namespace="http://www.ros.ie/schemas/customs/acknowledgerequest/v1" schemaLocation="customs/acknowledgerequest/v1/schema.xsd"/></xs:schema>
		<xs:schema><xs:import namespace="http://www.ros.ie/schemas/customs/acknowledgeresponse/v1" schemaLocation="customs/acknowledgeresponse/v1/schema.xsd"/></xs:schema>
	</wsdl:types>
		
		
	<wsdl:message name="MailboxAcknowledgeReq"><wsdl:part name="parameters" element="ackreq:MailboxAcknowledgeRequest"/></wsdl:message>
	<wsdl:message name="MailboxAcknowledgeRes"><wsdl:part name="parameters" element="ackres:MailboxAcknowledgeResponse"/></wsdl:message>
	
	
	<wsdl:portType name="MailboxAcknowledgePortType">
		<wsdl:operation name="MailboxAcknowledge">
			<wsdl:input message="MailboxAcknowledgeReq"/>
			<wsdl:output message="MailboxAcknowledgeRes"/>
		</wsdl:operation>
	</wsdl:portType>
	
	
	<wsdl:binding name="MailboxAcknowledgeSoapBinding" type="MailboxAcknowledgePortType">
		<soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="MailboxAcknowledge"><soap12:operation/>
			<wsdl:input><soap12:body use="literal"/></wsdl:input>
			<wsdl:output><soap12:body use="literal"/></wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	
	<wsdl:service name="MailboxAcknowledge">
		<wsdl:port name="MailboxAcknowledge" binding="MailboxAcknowledgeSoapBinding">
			<soap12:address location="https://www.ros.ie/customs/webservice/v1/soap/mailboxAcknowledge" />
		</wsdl:port>
	</wsdl:service>
	
	
</wsdl:definitions>
