<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!--

Document History:

======== Version 0.1 ====================================
	i. Document Created 01/04/2009
	
======== Version 0.2 ====================================
	i. Document updated 11/03/2020
		Updated wsdl for SOAP version 1.2

======== Version 0.3 ====================================
	i. Document updated 10/08/2023
		Added back missing namespaces definitions
-->

<wsdl:definitions 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
	xmlns:request="http://www.ros.ie/schemas/customs/transactionidrequest/v1" 
	xmlns:response="http://www.ros.ie/schemas/customs/transactionidresponse/v1" 
	xmlns="http://www.ros.ie/schemas/customs/service/TransactionID" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.ros.ie/schemas/customs/service/TransactionID" 
	name="transactionIDService">
	
	
	<wsdl:types>
		<xs:schema><xs:import namespace="http://www.ros.ie/schemas/customs/transactionidrequest/v1" schemaLocation="customs/transactionidrequest/v1/schema.xsd"/></xs:schema>
		<xs:schema><xs:import namespace="http://www.ros.ie/schemas/customs/transactionidresponse/v1" schemaLocation="customs/transactionidresponse/v1/schema.xsd"/></xs:schema>
	</wsdl:types>
	
	
	<wsdl:message name="TransactionIDRequest"><wsdl:part name="parameters" element="request:TransactionIDRequest"/></wsdl:message>
	<wsdl:message name="TransactionIDResponse"><wsdl:part name="parameters" element="response:TransactionIDResponse"/></wsdl:message>
	
	
	<wsdl:portType name="TransactionIDPortType">
		<wsdl:operation name="TransactionID">
			<wsdl:input message="TransactionIDRequest"/>
			<wsdl:output message="TransactionIDResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	
	<wsdl:binding name="TransactionIDSoapBinding" type="TransactionIDPortType">
		<soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="TransactionID">
			<soap12:operation/>
			<wsdl:input><soap12:body use="literal"/></wsdl:input>
			<wsdl:output><soap12:body use="literal"/></wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	
	<wsdl:service name="TransactionID">
		<wsdl:port name="TransactionID" binding="TransactionIDSoapBinding">
			<soap12:address location="https://www.ros.ie/customs/webservice/v1/soap/transactionID"/>
		</wsdl:port>
	</wsdl:service>
	
	
</wsdl:definitions>
